name: Crawl
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python crawler.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 自动更新磁力数据"
          file_pattern: data.js
